services:
  - type: web
    name: care-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
    healthCheckPath: "/health"
    autoDeploy: true